### ISSUE TITLE
Failure to load `LANG` env var

### ISSUE THREAD

**Issue by Nokel81** [sindresorhus/shell-env#16]
**Description:**
`shell-env` sometimes does not return all the environment variables that would be present after just starting a new terminal window.

**System:**
- OS: macos 10.15.3

**Related Issues:**
https://github.com/lensapp/lens/pull/492 and https://github.com/lensapp/lens/issues/351

This issue (and PR) are to fix `LANG` not being loaded properly.

**Specifics:**
It seems that macos (in particular) looks for the LANG env var to figure out how to send data to an application when pasting text. Namely, if one copies a unicode character from a web browser (firefox is what I tested) and paste it into a text region in an electron application, then the raw bytes that presented (to the JS using `Uint8Array`) change if `LANG=en_us.UTF-8` is subsequently added to the processes env collection.

**Comment by sindresorhus** [comment]
There's unfortunately not much I can do based on this information, since I cannot reproduce. A reproducible test case would go a long way. If you can reliably reproduce this on your machine, I would recommend trying to debug it a little bit. For example, try confirming that it detect the correct shell, and that running the shell normally with these commands: https://github.com/sindresorhus/shell-env/blob/a95fd441d3b7cc2c122899de72da30dae70936ec/index.js#L6-L9 outputs the expected result.
